"""Initial migrate

Revision ID: f7fca8b101c2
Revises: 
Create Date: 2023-11-20 13:33:31.355978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fca8b101c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=False),
    sa.Column('strength_bonus', sa.Integer(), nullable=True),
    sa.Column('vitality_bonus', sa.Integer(), nullable=True),
    sa.Column('armor_bonus', sa.Integer(), nullable=True),
    sa.Column('luck_bonus', sa.Integer(), nullable=True),
    sa.Column('dexterity_bonus', sa.Integer(), nullable=True),
    sa.Column('speed_bonus', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('vitality', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('exp_drop', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('dialogue', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('vitality', sa.Integer(), nullable=True),
    sa.Column('armor', sa.Integer(), nullable=True),
    sa.Column('luck', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('dungeon_level', sa.Integer(), nullable=True),
    sa.Column('highest_dungeon_level', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('equipped_melee_weapon_id', sa.Integer(), nullable=True),
    sa.Column('equipped_ranged_weapon_id', sa.Integer(), nullable=True),
    sa.Column('equipped_armor_id', sa.Integer(), nullable=True),
    sa.Column('equipped_ring_id', sa.Integer(), nullable=True),
    sa.Column('equipped_necklace_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_saved', sa.DateTime(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipped_armor_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['equipped_melee_weapon_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['equipped_necklace_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['equipped_ranged_weapon_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['equipped_ring_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loot_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('drop_chance', sa.Float(), nullable=True),
    sa.Column('monster_level', sa.Integer(), nullable=True),
    sa.Column('gold_drop', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npc_items',
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ),
    sa.PrimaryKeyConstraint('npc_id', 'item_id')
    )
    op.create_table('quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('exp_reward', sa.Integer(), nullable=True),
    sa.Column('item_reward_id', sa.Integer(), nullable=True),
    sa.Column('gold_reward', sa.Integer(), nullable=True),
    sa.Column('required_dungeon_level', sa.Integer(), nullable=True),
    sa.Column('target_amount', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_reward_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_items',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'item_id')
    )
    op.create_table('character_quest',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'quest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_quest')
    op.drop_table('character_items')
    op.drop_table('quest')
    op.drop_table('npc_items')
    op.drop_table('loot_table')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('npc')
    op.drop_table('monster')
    op.drop_table('item')
    # ### end Alembic commands ###
